change-template: "- $TITLE @$AUTHOR #$NUMBER"
sort-direction: ascending

name-template: "Release v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
tag-prefix: v

category-template: "### $TITLE"
categories:
  - type: "version-resolver"
    when:
      labels:
        - "major"
        - "breaking-change"
    semver-increment: "major"

  - type: "version-resolver"
    when:
      labels:
        - "feature"
    semver-increment: "minor"

  - type: "version-resolver"
    default: true
    when:
      labels:
        - "patch"
        - "bug"
        - "bugfix"
        - "dependencies"
    semver-increment: "patch"

  - title: ":boom: Breaking Changes"
    when:
      labels:
        - "breaking-change"

  - title: ":sparkles: New Features"
    when:
      labels:
        - "feature"

  - title: ":bug: Bug Fixes"
    when:
      labels:
        - "bug"
        - "bugfix"

  - title: "🧰 Maintenance"
    when:
      labels:
        - "chore"

  - title: ":recycle: Refactor"
    when:
      labels:
        - "refactor"

  - title: ":scroll: Documentation"
    when:
      labels:
        - "documentation"

  - title: ":arrow_up: Dependency Updates"
    when:
      labels:
        - "dependencies"
    collapse-after: 10

  - type: "pre-exclude"
    when:
      labels:
        - "ignore"

header: |

  ## What's Changed

template: |

  $CHANGES

footer: |

  ### Full Changelog
  [$PREVIOUS_TAG...v$RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)
