[files]
ignore-files = true
ignore-hidden = false
extend-exclude = [
    ".git/"
]

[default]
check-filename = true
extend-ignore-re = [
    "digest to [0-9a-f]+", # docker digests in changelog entries
]

[default.extend-words]
alls = "alls" # used by re-actors/alls-green action
