# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: "Reusable ci typos workflow"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  typos:
    name: 📝
    runs-on: ubuntu-slim
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: 📝 Check spelling using typos-action
        uses: crate-ci/typos@37bb98842b0d8c4ffebdb75301a13db0267cef89 # v1.47.2
