# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: "Reusable ci typos workflow"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  typos:
    name: 📝
    runs-on: ubuntu-slim
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: 📝 Check spelling using typos-action
        uses: crate-ci/typos@f8a58b6b53f2279f71eb605f03a4ae4d10608f45 # v1.47.0
