# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT

name: "Reusable ci typos workflow"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  typos:
    name: 📝
    runs-on: ubuntu-slim
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: 📝 Check spelling using typos-action
        uses: crate-ci/typos@7f9d0819ca1c008ade73f4b41fa9d258d48f605b # v1.51.1
